config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :rooms, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  validates :name, presence: true, uniqueness: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end
  
  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end  
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  def edit
  end

  private
  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    if @group.index(group)
      redirect_to group_rooms_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }
  .chat-group-form__errors
    %h2
      1件のエラーが発生しました。
      %ul
        %li エラーです
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_name"} グループ名
    .chat-group-form__field--right
      %input#chat_group_name.chat-group-form__input{name: "chat_group[name]", placeholder: "グループ名を入力してください", type: "text", value: "ほげー"}/
  .chat-group-form__field.clearfix
    / この部分はインクリメンタルサーチ(ユーザー追加の非同期化)のときに使用します
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_チャットメンバー"} チャットメンバー
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      / この部分はインクリメンタルサーチ(ユーザー追加の非同期化)のときにも使用します
      %input.chat-group-form__action-btn{"data-disable-with":"Save", name: "commit", type: "submit", value: "Save"}/

app/views/groups/index.html.haml
.wrapper
  = render partial: 'shared/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f|
    - if @group.errors.any?
      .chat-group-form__errors
        %h2= "#{@group.errors.full_messages.count}件のエラーが発生しました。"
        %ul
          - @group.errors.full_messages.each do |message|
            %li= message
    .chat-group-form__field
      .chat-group-form__field--left
        = f.label :name, class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
    .chat-group-form__field.clearfix
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化)のときに使用します
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label "チャットメンバー", class: "chat-group-form__label"
      .chat-group-form__field--right
        / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
        = f.collection_check_boxes :user_ids, User.all, :id, :name
        / この部分はインクリメンタルサーチ（ユーザー追加の非同期化)のときにも使用します
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit class: 'chat-group-form__action-btn'

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", http: { equiv: "Content-Type"}}
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/rooms/index.html.haml
.content
  .left-content
    .left-header
      .name 
        aono minoru 
      .menu-icons
        = link_to new_group_path do
          = fa_icon 'pencil-square-o', class: 'icon'
        = link_to edit_user_path(current_user) do
          = fa_icon 'cog', class: 'icon'
    .groups
      .group
        - current_user.groups.each do |group|
          = link_to group_rooms_path(group) do
            .group__name
              = group.name
            .group__message
              メッセージはまだありません。
  .chat-main
    .main-header
      .main-header_left-box 
        Hello world!
        .main-header_left-box_member_list 
          Member
      -# = link_to edit_group_path(@group) do
      -#   = edit type: 'submit', value: 'Edit'

    .content-main__chat
      .data-chat_id
        .chat_upper-info
          %p.chat_upper-info_talker hello
          %p.chat_upper-info_date 2019
        %p.message_text hey!
    .footer   
      .input-box
      %input.login-input-text{name: "type-a-message", placeholder: "type a message", type: "text", value: ""}/
      .menu-icons
        = link_to "#", class: "content__btn" do
          = fa_icon 'picture-o'
      %input.submit{type: "submit", value: "send"}

app/views/rooms/show.html.haml
.content
  .left-content
    .left-header
      .name 
        aono minoru 
      .menu-icons
        = link_to "#", class: "content__btn" do
          = fa_icon 'pencil-square-o'
        = link_to "#", class: "content__btn" do
          = fa_icon 'cog'
    .groups
      .group
        %p.group_group-name Team abc
        %p.group_latest-message Hello world!
  .chat-main
    .main-header
      .main-header_left-box 
        Hello world!
        .main-header_left-box_member_list 
          Member
      %input.edit{type: "submit", value: "Edit"}

    .content-main__chat
      .data-chat_id
        .chat_upper-info
          %p.chat_upper-info_talker hello
          %p.chat_upper-info_date 2019
        %p.message_text hey!
    .footer   
      .input-box
      %input.login-input-text{name: "type-a-message", placeholder: "type a message", type: "text", value: ""}/
      .menu-icons
        = link_to "#", class: "content__btn" do
          = fa_icon 'picture-o'
      %input.submit{type: "submit", value: "send"}

app/views/shared/_side_bar.html.haml
.left-content
  .left-header
    .name 
      = current_user.name
    .menu-icons
      = link_to new_group_path do
        = fa_icon 'pencil-square-o', class: 'icon'
      = link_to edit_user_path(current_user) do
        = fa_icon 'cog', class: 'icon'
  .groups
    - current_user.groups.each do |group|
      .group
        = link_to group_rooms_path(group) do
          .group__name
            = group.name
          .group__message
            メッセージはまだありません。

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'